In [1]:
# Predicting outputs and sending the data to MySQL

In [8]:
import pickle
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
import pymysql

In [3]:
# Making Predictions

In [16]:
model=pickle.load(open('model','rb'))

In [17]:
model

RandomForestClassifier(max_depth=8, max_features=15, min_samples_leaf=30,
                       min_samples_split=48, n_estimators=410, n_jobs=-1,
                       random_state=20)

In [18]:
test=pd.read_csv('Test_Data.csv')
test

,Group_1_Reason,Group_2_Reason,Group_3_Reason,Group_4_Reason,Month,Day,Transportation_Expense,Distance,Age,Workload,Hit_Target,Disciplinary_Failure,Education,Son,Social drinker,Social smoker,Pet,BMI
0,0,0,0,1,5,4,291,31,40,237656,99,0,0,1,1,0,1,25
1,1,0,0,0,6,6,246,25,41,377550,94,0,0,0,1,0,0,23
2,1,0,0,0,2,4,233,51,31,264249,97,0,1,1,1,0,8,21
3,0,0,0,1,1,4,179,51,38,313532,96,0,0,0,1,0,0,31
4,0,0,0,1,6,2,179,51,38,253957,95,0,0,0,1,0,0,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,0,0,0,1,1,3,225,26,28,308593,95,0,0,1,0,0,2,24
144,0,0,0,1,12,5,235,11,37,236629,93,0,1,1,0,0,1,29
145,0,0,0,1,4,2,179,51,38,239409,98,0,0,0,1,0,0,31
146,0,0,0,1,7,3,289,36,33,239554,97,0,0,2,1,0,1,30
147,0,0,1,0,6,5,118,13,50,275089,96,0,0,1,1,0,0,31

In [26]:
test.columns

Index(['Group_1_Reason', 'Group_2_Reason', 'Group_3_Reason', 'Group_4_Reason',
       'Month', 'Day', 'Transportation_Expense', 'Distance', 'Age', 'Workload',
       'Hit_Target', 'Disciplinary_Failure', 'Education', 'Son',
       'Social drinker', 'Social smoker', 'Pet', 'BMI', 'Predicton',
       'Probability'],
      dtype='object')

In [21]:
pred=model.predict(test)
prob=model.predict_proba(test)[:,1]

In [22]:
test['Predicton']=pred
test['Probability']=prob
test

,Group_1_Reason,Group_2_Reason,Group_3_Reason,Group_4_Reason,Month,Day,Transportation_Expense,Distance,Age,Workload,Hit_Target,Disciplinary_Failure,Education,Son,Social drinker,Social smoker,Pet,BMI,Predicton,Probability
0,0,0,0,1,5,4,291,31,40,237656,99,0,0,1,1,0,1,25,0,0.406268
1,1,0,0,0,6,6,246,25,41,377550,94,0,0,0,1,0,0,23,1,0.791293
2,1,0,0,0,2,4,233,51,31,264249,97,0,1,1,1,0,8,21,1,0.757568
3,0,0,0,1,1,4,179,51,38,313532,96,0,0,0,1,0,0,31,0,0.083849
4,0,0,0,1,6,2,179,51,38,253957,95,0,0,0,1,0,0,31,0,0.332363
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,0,0,0,1,1,3,225,26,28,308593,95,0,0,1,0,0,2,24,0,0.106842
144,0,0,0,1,12,5,235,11,37,236629,93,0,1,1,0,0,1,29,0,0.457500
145,0,0,0,1,4,2,179,51,38,239409,98,0,0,0,1,0,0,31,0,0.298192
146,0,0,0,1,7,3,289,36,33,239554,97,0,0,2,1,0,1,30,1,0.669238
147,0,0,1,0,6,5,118,13,50,275089,96,0,0,1,1,0,0,31,1,0.592862

In [39]:
test.shape[1]

20

# Connecting to My_SQL

In [27]:
conn=pymysql.connect(database='Leave_outputs',user='root',password='samarth')

In [28]:
cursor=conn.cursor()

In [29]:
query='select * from Predicted_outputs;'

In [32]:
cursor.execute(query)

0

In [33]:
# Creating the Insert Statement

In [35]:
insert='insert into Predicted_outputs values'
for i in range(test.shape[0]):
    insert +='('
    for j in range(test.shape[1]):
        insert += str(test.iloc[i,j]) +','
    insert=insert[:-2]+')';
    print(insert)
    #cursor.execute(insert)
    #conn.commit()
    #insert='insert into Predicted_outputs values'

insert into Predicted_outputs values(0,0,0,1,5,4,291,31,40,237656,99,0,0,1,1,0,1,25,0,0.4062684536091404)
insert into Predicted_outputs values(1,0,0,0,6,6,246,25,41,377550,94,0,0,0,1,0,0,23,1,0.791293495487153)
insert into Predicted_outputs values(1,0,0,0,2,4,233,51,31,264249,97,0,1,1,1,0,8,21,1,0.757568110802272)
insert into Predicted_outputs values(0,0,0,1,1,4,179,51,38,313532,96,0,0,0,1,0,0,31,0,0.0838487680321900)
insert into Predicted_outputs values(0,0,0,1,6,2,179,51,38,253957,95,0,0,0,1,0,0,31,0,0.332362820468565)
insert into Predicted_outputs values(0,0,0,1,2,3,179,26,30,302585,99,0,1,0,0,0,0,19,0,0.156499601458758)
insert into Predicted_outputs values(0,0,0,1,11,4,225,26,28,306345,93,0,0,1,0,0,2,24,0,0.2171202484670001)
insert into Predicted_outputs values(0,0,0,1,10,3,179,51,38,253465,93,0,0,0,1,0,0,31,0,0.2502785887331898)
insert into Predicted_outputs values(0,0,0,1,8,3,179,22,40,249797,93,0,1,2,0,1,0,22,0,0.394826663534502)
insert into Predicted_outputs values(0,0,0,1,10,2,369,17,31,265017,88,0,0,3,1,0,0,25,1,0.582785835936613)
insert into Predicted_outputs values(0,0,0,1,8,6,260,50,36,265615,94,0,0,4,1,0,0,23,1,0.618068588520111)
insert into Predicted_outputs values(1,0,0,0,5,2,361,52,28,237656,99,0,0,1,1,0,4,27,1,0.8146537390780)
insert into Predicted_outputs values(0,0,0,1,6,2,118,10,37,275089,96,0,0,0,0,0,0,28,0,0.3467679593681109)
insert into Predicted_outputs values(1,0,0,0,10,5,289,48,49,284853,91,0,0,0,0,0,2,36,1,0.645344752107671)
insert into Predicted_outputs values(1,0,0,0,11,4,260,50,36,284031,97,0,0,4,1,0,0,23,1,0.827915688763280)
insert into Predicted_outputs values(0,0,1,0,9,4,225,26,28,241476,92,0,0,1,0,0,2,24,1,0.550206097726352)
insert into Predicted_outputs values(0,0,0,1,8,4,248,25,47,205917,92,0,0,2,0,0,1,32,0,0.413664099123441)
insert into Predicted_outputs values(0,0,0,1,11,5,235,11,37,284031,97,0,1,1,0,0,1,29,0,0.4216152254444736)
insert into Predicted_outputs values(0,0,0,1,8,5,235,11,37,205917,92,0,1,1,0,0,1,29,1,0.531626445024229)
insert into Predicted_outputs values(0,0,0,1,12,5,225,26,28,280549,98,0,0,1,0,0,2,24,0,0.2049471635071823)
insert into Predicted_outputs values(0,0,0,1,3,4,369,17,31,222196,99,0,0,3,1,0,0,25,1,0.587034940683749)
insert into Predicted_outputs values(0,0,0,0,11,4,289,36,33,268519,93,1,0,2,1,0,1,30,1,0.682755385128741)
insert into Predicted_outputs values(1,0,0,0,10,4,228,14,58,284853,91,0,0,2,0,0,1,22,1,0.614927165758729)
insert into Predicted_outputs values(1,0,0,0,11,5,118,10,37,268519,93,0,0,0,0,0,0,28,1,0.556970671194636)
insert into Predicted_outputs values(0,0,1,0,4,2,225,26,28,246288,91,0,0,1,0,0,2,24,1,0.564159448562356)
insert into Predicted_outputs values(0,0,0,1,9,6,260,50,36,294217,81,0,0,4,1,0,0,23,1,0.605959702210809)
insert into Predicted_outputs values(0,0,0,1,5,5,235,16,32,237656,99,0,1,0,0,0,0,25,0,0.452253952566304)
insert into Predicted_outputs values(0,0,0,1,11,5,291,31,40,306345,93,0,0,1,1,0,1,25,0,0.3711778946387524)
insert into Predicted_outputs values(1,0,0,0,9,4,246,25,41,294217,81,0,0,0,1,0,0,23,1,0.781881748822984)
insert into Predicted_outputs values(0,0,0,1,10,4,179,51,38,284853,91,0,0,0,1,0,0,31,0,0.2323420847532700)
insert into Predicted_outputs values(0,0,0,1,11,3,361,52,28,268519,93,0,0,1,1,0,4,27,1,0.527603380431923)
insert into Predicted_outputs values(1,0,0,0,7,4,179,51,38,239554,97,0,0,0,1,0,0,31,1,0.71996204205389)
insert into Predicted_outputs values(0,0,0,1,11,6,225,26,28,268519,93,0,0,1,0,0,2,24,0,0.2268346555032685)
insert into Predicted_outputs values(0,0,0,1,3,6,260,50,36,343253,95,0,0,4,1,0,0,23,1,0.596506219706727)
insert into Predicted_outputs values(1,0,0,0,4,5,289,36,33,326452,96,0,0,2,1,0,1,30,1,0.842602319333713)
insert into Predicted_outputs values(0,0,1,0,5,3,225,26,28,378884,92,0,0,1,0,0,2,24,1,0.565660133771016)
insert into Predicted_outputs values(0,0,0,1,11,4,289,36,33,268519,93,0,0,2,1,0,1,30,1,0.655312008168459)
insert into Predicted_outputs values(1,0,0,0,6,2,179,51,38,377550,94,0,0,0,1,0,0,31,1,0.743435781617248)
insert into Predicted_outputs values(1,0,0,0,6,4,118,10,37,275089,96,0,0,0,0,0,0,28,1,0.556626216107103)
insert into Predicted_outputs values(0,0,0,1,7,2,235,29,48,230290,92,0,0,1,0,1,5,33,0,0.4158840048459309)
insert into Predicted_outputs values(0,0,0,1,5,4,225,26,28,246074,99,0,0,1,0,0,2,24,0,0.265331131138132)
insert into Predicted_outputs values(0,0,1,0,6,4,179,26,30,253957,95,0,1,0,0,0,0,19,1,0.558911099337750)
insert into Predicted_outputs values(1,0,0,0,8,5,268,11,33,265615,94,0,1,0,0,0,0,25,1,0.639983779754942)
insert into Predicted_outputs values(1,0,0,0,2,5,179,51,38,251818,96,0,0,0,1,0,0,31,1,0.711454233933490)
insert into Predicted_outputs values(1,0,0,0,2,4,179,51,38,302585,99,0,0,0,1,0,0,31,1,0.743788069998081)
insert into Predicted_outputs values(0,0,0,1,2,4,179,51,38,251818,96,0,0,0,1,0,0,31,0,0.0993671746095722)
insert into Predicted_outputs values(1,0,0,0,7,2,260,50,36,239554,97,0,0,4,1,0,0,23,1,0.833094204727021)
insert into Predicted_outputs values(0,0,0,1,3,4,179,51,38,222196,99,0,0,0,1,0,0,31,0,0.1981402044526372)
insert into Predicted_outputs values(0,0,0,1,12,4,291,31,40,280549,98,0,0,1,1,0,1,25,0,0.374152504675274)
insert into Predicted_outputs values(1,0,0,0,10,6,225,26,28,284853,91,0,0,1,0,0,2,24,1,0.551912734959459)
insert into Predicted_outputs values(0,0,1,0,7,3,155,12,34,275312,98,0,0,2,1,0,0,25,1,0.684470012780616)
insert into Predicted_outputs values(0,0,0,1,9,5,118,13,50,294217,81,0,0,1,1,0,0,31,0,0.257729153688881)
insert into Predicted_outputs values(0,0,0,1,9,6,248,25,47,241476,92,0,0,2,0,0,1,32,0,0.390917301963247)
insert into Predicted_outputs values(1,0,0,0,10,2,179,26,30,265017,88,0,1,0,0,0,0,19,1,0.54686049900850)
insert into Predicted_outputs values(0,0,0,1,11,4,291,31,40,268519,93,0,0,1,1,0,1,25,0,0.376647959896332)
insert into Predicted_outputs values(1,0,0,0,11,5,225,26,28,268519,93,0,0,1,0,0,2,24,1,0.544486994298376)
insert into Predicted_outputs values(0,0,0,1,8,3,289,36,33,249797,93,0,0,2,1,0,1,30,1,0.66591303222005)
insert into Predicted_outputs values(0,0,1,0,2,5,189,29,33,302585,99,0,0,2,0,0,2,25,1,0.646743796686413)
insert into Predicted_outputs values(0,0,0,1,1,6,179,22,40,313532,96,0,1,2,0,1,0,22,0,0.2355808172404573)
insert into Predicted_outputs values(1,0,0,0,10,5,369,17,31,284853,91,0,0,3,1,0,0,25,1,0.794278458931395)
insert into Predicted_outputs values(0,0,0,1,1,2,155,12,34,330061,100,0,0,2,1,0,0,25,0,0.342666451722308)
insert into Predicted_outputs values(1,0,0,0,6,2,291,31,40,253957,95,0,0,1,1,0,1,25,1,0.797174329594339)
insert into Predicted_outputs values(0,0,0,1,5,4,179,26,30,246074,99,0,1,0,0,0,0,19,0,0.261145925848126)
insert into Predicted_outputs values(0,0,0,1,11,6,179,51,38,268519,93,0,0,0,1,0,0,31,0,0.23249422146108)
insert into Predicted_outputs values(1,0,0,0,6,6,235,11,37,377550,94,0,1,1,0,0,1,29,1,0.620251673052520)
insert into Predicted_outputs values(1,0,0,0,11,4,330,16,28,268519,93,0,1,0,0,0,0,25,1,0.632995328348579)
insert into Predicted_outputs values(0,0,0,1,3,3,228,14,58,222196,99,0,0,2,0,0,1,22,0,0.35617569899375)
insert into Predicted_outputs values(0,0,0,1,4,3,118,13,50,246288,91,0,0,1,1,0,0,31,0,0.283454810271440)
insert into Predicted_outputs values(1,0,0,0,4,2,118,10,37,246288,91,0,0,0,0,0,0,28,1,0.55904452150166)
insert into Predicted_outputs values(1,0,0,0,4,2,225,26,28,246288,91,0,0,1,0,0,2,24,1,0.548791420754694)
insert into Predicted_outputs values(0,0,0,1,2,5,155,12,34,302585,99,0,0,2,1,0,0,25,0,0.3256165070177296)
insert into Predicted_outputs values(0,0,1,0,2,2,330,16,28,302585,99,0,1,0,0,0,0,25,1,0.609461265224754)
insert into Predicted_outputs values(1,0,0,0,10,4,289,48,49,284853,91,0,0,0,0,0,2,36,1,0.647347527771443)
insert into Predicted_outputs values(1,0,0,0,4,5,118,13,50,246288,91,0,0,1,1,0,0,31,1,0.683633113396294)
insert into Predicted_outputs values(0,0,0,1,2,6,289,36,33,251818,96,0,0,2,1,0,1,30,1,0.628949490500427)
insert into Predicted_outputs values(0,0,0,1,9,3,246,25,41,261756,87,0,0,0,1,0,0,23,0,0.3314438638507200)
insert into Predicted_outputs values(0,0,0,1,6,5,225,26,28,377550,94,0,0,1,0,0,2,24,0,0.280372119637580)
insert into Predicted_outputs values(1,0,0,0,11,3,118,10,37,268519,93,0,0,0,0,0,0,28,1,0.565965947747525)
insert into Predicted_outputs values(1,0,0,0,5,3,179,51,38,378884,92,0,0,0,1,0,0,31,1,0.736352277945260)
insert into Predicted_outputs values(0,0,0,1,5,6,361,52,28,378884,92,0,0,1,1,0,4,27,1,0.520344811884398)
insert into Predicted_outputs values(0,0,0,1,12,3,225,26,28,280549,98,0,0,1,0,0,2,24,0,0.2099503810248698)
insert into Predicted_outputs values(0,0,0,1,1,4,118,10,37,308593,95,0,0,0,0,0,0,28,0,0.1148908644001672)
insert into Predicted_outputs values(0,0,0,1,9,3,155,12,34,261756,87,0,0,2,1,0,0,25,0,0.4057124640979455)
insert into Predicted_outputs values(1,0,0,0,5,4,289,36,33,378884,92,0,0,2,1,0,1,30,1,0.826576253876530)
insert into Predicted_outputs values(0,0,0,0,10,6,118,13,50,265017,88,1,0,1,1,0,0,31,0,0.3833649841240392)
insert into Predicted_outputs values(1,0,0,0,7,5,189,29,33,239554,97,0,0,2,0,0,2,25,1,0.596381496379832)
insert into Predicted_outputs values(0,0,0,1,3,5,225,26,28,222196,99,0,0,1,0,0,2,24,0,0.1855174955333778)
insert into Predicted_outputs values(1,0,0,0,3,4,260,50,36,343253,95,0,0,4,1,0,0,23,1,0.834627387174752)
insert into Predicted_outputs values(0,0,0,1,1,2,179,26,30,313532,96,0,1,0,0,0,0,19,0,0.0975161751377376)
insert into Predicted_outputs values(0,0,1,0,5,3,179,51,38,378884,92,0,0,0,1,0,0,31,1,0.614710105010844)
insert into Predicted_outputs values(0,0,0,1,7,6,361,52,28,230290,92,0,0,1,1,0,4,27,1,0.58751372342926)
insert into Predicted_outputs values(0,0,0,1,5,4,235,16,32,237656,99,0,1,0,0,0,0,25,0,0.4553265235064184)
insert into Predicted_outputs values(1,0,0,0,12,3,235,20,43,236629,93,0,0,1,1,0,0,38,1,0.74944215714845)
insert into Predicted_outputs values(0,0,0,1,1,3,118,10,37,308593,95,0,0,0,0,0,0,28,0,0.126271123982243)
insert into Predicted_outputs values(0,0,0,1,2,2,155,12,34,264249,97,0,0,2,1,0,0,25,0,0.3058375329924797)
insert into Predicted_outputs values(1,0,0,0,2,3,388,15,50,302585,99,0,0,0,0,0,0,24,1,0.647364217766279)
insert into Predicted_outputs values(0,0,0,1,9,4,235,20,43,294217,81,0,0,1,1,0,0,38,0,0.3406294256670881)
insert into Predicted_outputs values(0,0,0,1,4,4,330,16,28,239409,98,0,1,0,0,0,0,25,0,0.4887822414755615)
insert into Predicted_outputs values(1,0,0,0,5,6,330,16,28,246074,99,0,1,0,0,0,0,25,1,0.625666001099639)
insert into Predicted_outputs values(0,0,1,0,11,4,179,22,40,306345,93,0,1,2,0,1,0,22,1,0.583053996096260)
insert into Predicted_outputs values(1,0,0,0,11,6,291,31,40,284031,97,0,0,1,1,0,1,25,1,0.791338328660288)
insert into Predicted_outputs values(0,0,0,0,4,2,235,29,48,326452,96,1,0,1,0,1,5,33,0,0.457292559671998)
insert into Predicted_outputs values(0,0,0,1,10,3,369,17,31,284853,91,0,0,3,1,0,0,25,1,0.57819323051818)
insert into Predicted_outputs values(0,0,0,1,11,2,235,20,43,284031,97,0,0,1,1,0,0,38,0,0.3256003956752910)
insert into Predicted_outputs values(1,0,0,0,7,2,330,16,28,275312,98,0,1,0,0,0,0,25,1,0.638392070115552)
insert into Predicted_outputs values(0,0,0,1,3,6,118,13,50,244387,98,0,0,1,1,0,0,31,0,0.2079073782579874)
insert into Predicted_outputs values(0,0,0,1,8,2,289,36,33,265615,94,0,0,2,1,0,1,30,1,0.667555836491380)
insert into Predicted_outputs values(0,0,0,1,10,4,291,31,40,284853,91,0,0,1,1,0,1,25,0,0.373088762641404)
insert into Predicted_outputs values(0,0,0,1,4,6,179,26,30,246288,91,0,1,0,0,0,0,19,0,0.240209907461168)
insert into Predicted_outputs values(0,0,0,1,8,6,235,29,48,205917,92,0,0,1,0,1,5,33,0,0.4086765170007795)

insert into Predicted_outputs values(0,0,1,0,12,3,118,10,37,261306,97,0,0,0,0,0,0,28,1,0.560994341612203)
insert into Predicted_outputs values(0,0,0,1,7,6,361,52,28,239554,97,0,0,1,1,0,4,27,1,0.583092500504778)
insert into Predicted_outputs values(0,0,0,1,2,2,179,51,38,251818,96,0,0,0,1,0,0,31,0,0.1121967662973967)
insert into Predicted_outputs values(0,0,0,1,9,4,225,26,28,261756,87,0,0,1,0,0,2,24,0,0.265296586646341)
insert into Predicted_outputs values(1,0,0,0,6,6,118,10,37,275089,96,0,0,0,0,0,0,28,1,0.553975885035136)
insert into Predicted_outputs values(1,0,0,0,10,3,291,31,40,253465,93,0,0,1,1,0,1,25,1,0.785436919880710)
insert into Predicted_outputs values(0,0,0,1,2,4,179,26,30,264249,97,0,1,0,0,0,0,19,0,0.092333207732791)
insert into Predicted_outputs values(0,0,0,1,9,6,179,51,38,241476,92,0,0,0,1,0,0,31,0,0.293047528511070)
insert into Predicted_outputs values(0,0,0,1,11,4,225,26,28,306345,93,0,0,1,0,0,2,24,0,0.2171202484670001)
insert into Predicted_outputs values(0,0,0,0,9,3,291,50,32,294217,81,1,0,0,1,0,0,23,1,0.570160570862455)
insert into Predicted_outputs values(0,0,0,0,10,6,248,25,47,265017,88,1,0,2,0,0,1,32,0,0.45520189171398)
insert into Predicted_outputs values(0,0,0,1,11,2,291,31,40,284031,97,0,0,1,1,0,1,25,0,0.3733467566992113)
insert into Predicted_outputs values(0,0,0,1,4,6,179,26,30,246288,91,0,1,0,0,0,0,19,0,0.240209907461168)
insert into Predicted_outputs values(0,0,0,1,11,5,179,51,38,306345,93,0,0,0,1,0,0,31,0,0.225898983958667)
insert into Predicted_outputs values(0,0,0,0,3,4,369,17,31,244387,98,1,0,3,1,0,0,25,1,0.630001199647925)
insert into Predicted_outputs values(0,0,0,1,5,4,155,12,34,237656,99,0,0,2,1,0,0,25,0,0.419201962724161)
insert into Predicted_outputs values(0,0,0,1,3,4,289,36,33,222196,99,0,0,2,1,0,1,30,1,0.65679054888850)
insert into Predicted_outputs values(0,0,0,1,4,6,235,11,37,246288,91,0,1,1,0,0,1,29,0,0.457827037416951)
insert into Predicted_outputs values(0,0,0,1,2,6,260,50,36,302585,99,0,0,4,1,0,0,23,1,0.588441037203074)
insert into Predicted_outputs values(1,0,0,0,2,3,179,51,38,264249,97,0,0,0,1,0,0,31,1,0.716523305965980)
insert into Predicted_outputs values(0,0,0,0,5,3,118,13,50,237656,99,1,0,1,1,0,0,31,0,0.4540926581613358)
insert into Predicted_outputs values(0,0,0,1,8,5,330,16,28,249797,93,0,1,0,0,0,0,25,1,0.544696435594046)
insert into Predicted_outputs values(0,0,0,1,10,6,291,31,40,284853,91,0,0,1,1,0,1,25,0,0.3714261609047639)
insert into Predicted_outputs values(1,0,0,0,11,5,248,25,47,268519,93,0,0,2,0,0,1,32,1,0.609651605232854)
insert into Predicted_outputs values(0,1,0,0,4,3,235,16,32,246288,91,0,1,0,0,0,0,25,0,0.488007592631329)
insert into Predicted_outputs values(1,0,0,0,7,3,330,16,28,275312,98,0,1,0,0,0,0,25,1,0.635460332580781)
insert into Predicted_outputs values(0,0,0,1,8,5,179,26,30,265615,94,0,1,0,0,0,0,19,0,0.302794582841560)
insert into Predicted_outputs values(1,0,0,0,3,2,225,26,28,343253,95,0,0,1,0,0,2,24,1,0.578540106243490)
insert into Predicted_outputs values(0,0,0,1,10,4,179,51,38,265017,88,0,0,0,1,0,0,31,0,0.2383345480943712)
insert into Predicted_outputs values(0,0,0,1,7,6,179,51,38,239554,97,0,0,0,1,0,0,31,0,0.335448334048512)
insert into Predicted_outputs values(0,0,0,1,6,5,291,31,40,377550,94,0,0,1,1,0,1,25,0,0.405771493704485)
insert into Predicted_outputs values(0,0,0,0,6,2,235,29,48,275089,96,1,0,1,0,1,5,33,0,0.4772009366711092)
insert into Predicted_outputs values(0,0,0,1,12,4,361,52,28,261306,97,0,0,1,1,0,4,27,1,0.529533758662348)
insert into Predicted_outputs values(0,0,0,1,1,3,225,26,28,308593,95,0,0,1,0,0,2,24,0,0.1068415649354287)
insert into Predicted_outputs values(0,0,0,1,12,5,235,11,37,236629,93,0,1,1,0,0,1,29,0,0.457500353815564)
insert into Predicted_outputs values(0,0,0,1,4,2,179,51,38,239409,98,0,0,0,1,0,0,31,0,0.2981923860429064)
insert into Predicted_outputs values(0,0,0,1,7,3,289,36,33,239554,97,0,0,2,1,0,1,30,1,0.669237639872555)
insert into Predicted_outputs values(0,0,1,0,6,5,118,13,50,275089,96,0,0,1,1,0,0,31,1,0.592861861804515)

In [36]:
conn.close()